### PR TITLE
Create german translation (de-DE)

### PR DESCRIPTION
**Pull request by Staubgeborener**
I think around 90-95% is translated. In the German language, however, many English anglicisms are also used, so it should be fine so far.

### CODE REVIEW

**Comment by CasperH2O** [comment]
Wow! Nice work @Staubgeborener .

**Comment by Valkirie** [comment]
Thanks for your work. Can you fix SettingsPage.xaml.cs though? Looks like a formatting issue.

**Comment by Staubgeborener** [comment]
> Thanks for your work. Can you fix SettingsPage.xaml.cs though? Looks like a formatting issue.

fix'd

**Comment by Staubgeborener** [comment]
> Thanks for your work. Can you fix SettingsPage.xaml.cs though? Looks like a formatting issue.

I can't quite figure out exactly where the problem is. I used the file fresh from the original repo (main branch) and edited it again, but it still seems to be the same problem. Feel free to add the one line yourself otherwise.

**Comment by Valkirie** [comment]
image
This is the issue. Could it be you got a warning from VS when you opened that file ? Something that has to do with end of line ?

**Comment by Staubgeborener** [comment]
@Valkirie Nope, nothing like that. The first edit of the `SettingsPage.xaml.cs` file was inside a browser, the second edit with VS - like i said, i copied the original file into my fork and edited it. When I do the same procedure again and add the one line and then commit it, I get a "Your branch is up to date with 'origin/main'." message in VS as VS seems to just check the hash (?). 

The only possibility I see here is to close the PR and open a new one to start from zero.

**Comment by Staubgeborener** [comment]
Ok, issue seems to be `LF will be replaced by CRLF the next time Git touches it`, i will re-create this PR

**Pull request closed without merging**
