### PR TITLE
Performance updates, breaks profile compatibility unfortunately

### PR DESCRIPTION
**Pull request by Havner**
Replace Dictionary with SortedDictionary in several place where it makes sense.

Replace ContainsKey() and [] later with TryGetValue() in all places I found.

### CODE REVIEW

**Comment by Valkirie** [comment]
Couldn't find any regressions.

**Comment by Havner** [comment]
I've pushed minor cleanup with _using_ for List.

**Comment by Havner** [comment]
To convert old profiles you can use this sed:

```
$ sed -i -e 's#Dictionary\(.*\)System.Private.CoreLib"#SortedDictionary\1System.Collections"#g' *.json
```

**Comment by Valkirie** [comment]
Let's add this regex check on top of the process profile function.
I'll also add a version field to profile so we actually know which build produced them.

**Comment by Valkirie** [comment]
I'm closing on layout export and will look into this one.

**Comment by Valkirie** [comment]
Added support for previous Profiles and implemented Profile versioning

**Pull request merged**
