### PR TITLE
ROG Ally, fix back button OEM3 hotkey usage after firmware update.

### PR DESCRIPTION
**Pull request by CasperH2O**

### CODE REVIEW

**Comment by Valkirie** [comment]
Feel free to add more buttons from here: https://github.com/seerge/g-helper/commit/8d9999c6c737c7f30bd8da8746f997bdea0c515c

**Comment by cra88y** [comment]
merge this. I wasted hours trying to troubleshoot this issue

**Comment by CasperH2O** [comment]
> merge this. I wasted hours trying to troubleshoot this issue

Sorry to hear about your troubles, but that's not a very polite way of asking. 🙃

**Comment by cra88y** [comment]
> > merge this. I wasted hours trying to troubleshoot this issue
> 
> Sorry to hear about your troubles, but that's not a very polite way of asking. 🙃

I apologize, I did not intend to come across as rude just wanted to draw attention to the PR

**Comment by theastadler** [comment]
Sorry, I usually just download the "release" from here, but the only one available doesn't have this fix. What should I do to have it on my device without having to wait for a new release?

**Comment by cra88y** [comment]
> Sorry, I usually just download the "release" from here, but the only one available doesn't have this fix. What should I do to have it on my device without having to wait for a new release?

The maintainer intends to release 18.0 this Saturday so that may be preferrable to the other option which is on the discord server in the rog-asus channel I made a recent post on how you can build the current branch yourself.

**Pull request merged**
