### PR TITLE
Initial russian translation

### PR DESCRIPTION
**Pull request by Geckon01**

### CODE REVIEW

**Comment by CasperH2O** [comment]
Amazing work Andrew, thank you. I've started the build check (it's for first time PRs from new people). 

Are you planning on doing the common and controller service resource.resx files also? They are luckily not so big as the HC one. They are located here:

https://github.com/Valkirie/HandheldCompanion/tree/main/ControllerCommon/Properties
https://github.com/Valkirie/HandheldCompanion/tree/main/ControllerService/Properties

**Comment by Geckon01** [comment]
Yeah, I'm planning this too later.

**Comment by CasperH2O** [comment]
> Yeah, I'm planning this too later.

Sure @Geckon01 , do you want this PR to remain open until then or would you like it merged?

**Comment by Geckon01** [comment]
I'd like to merge it. There are russian forums and social network where some people waiting for update with a translation. So if this PR will be in next update I can get more feedback.

**Comment by CasperH2O** [comment]
@Geckon01 sounds good. @Valkirie what do you think, shall we merge (rebase) this into main?

**Pull request merged**
