### PR TITLE
Add an option to enable desktop profile on application start

### PR DESCRIPTION
**Pull request by Havner**
By default it's true and has a nice side effect of making the mouse/keyboard work automatically on first HC start after it's installed.

### CODE REVIEW

**Comment by Havner** [comment]
It's just a proposal/RFC. I mean the code is ready and working but not sure you actually want something like that. But hear me out please.

We've discussed today two main ways people can use HC:

1. Desktop mode is the main profile for the desktop and the Default profile is a profile for most games with specific games getting their own profile. This requires hitting a hotkey when starting/leaving the game. This is what probably most people use.

2. Default mode is the main profile for the desktop. All games need their own profile but the profiles switch automatically on game start/stop. No hotkey required. This is what I use and for what I reported many bugreports. To have this mode working flawlessly (and it does now).

Now Benjamin mentioned today that he likes the 2 so much now that it would consider making it the de facto default. I've talked with Casper later about that and he told me that for several people this might be off-putting cause it requires creating profiles for all games. I honestly get that argument.

And probably no rework/change of paradigm won't happen any time soon (not that it needs) and the current state of HC actually supports both approaches. I just feel there is one option missing to improve it. Hence this PR.

Adding such an option will be helpful for people using 1. Actually one user even asked for this to happen automatically (enabled Desktop profile on start). And before someone does that I created an option for that because for people using 2 this is not what they want.

This option and its default value being true has one more effect, that actually benefits people using 1 and 2. When you start HC for the first time ever you have the Desktop profile automatically enabled and mouse/basic keyboard working out of the box. And then you can choose what to do and which way to go.

**Comment by CasperH2O** [comment]
Perhaps slightly late as you already went through the effort, but instead of having a setting for this, why not fix the bug that if you have Desktop layout active when closing HC, it will be active again when you open HC?

**Comment by CasperH2O** [comment]
In response to your proposal, I'm personally a big fan of number 2 but want to caution restrain for new users. Perhaps we can:
- Add Desktop mode pinned to QuickTools by default
- Enable Desktop mode by default
- Fix Desktop mode enable/disable state through HC restarts

That drawback here is that when people start playing games, they need to learn how to disable Desktop mode... Which I really don't like. 🙁

**Comment by Havner** [comment]
> Perhaps slightly late as you already went through the effort, but instead of having a setting for this, why not fix the bug that if you have Desktop layout active when closing HC, it's not active again when you open HC, currently it's always disabled when opening HC regardless?

It's not a bug from what I can see from the code. The Desktop profile setting is marked as temporary and has been from the start. And I personally don't like it to be restored. In my mind it really is the temporary setting. I might close the HC in various states but it doesn't change the paradigm in which I use HC. And I want it to be in a known state when I start it.

**Comment by Havner** [comment]
>     * Add Desktop mode pinned to QuickTools by default
Sure

>     * Enable Desktop mode by default
My code makes it enabled by default on first HC start. But you can disable that later on if you choose to.

>     * Fix Desktop mode enable/disable state through HC restarts
This is exactly what I don't want. 

> The drawback here is that when people start playing games, they need to learn how to disable Desktop mode... Which I really don't like. 🙁

From what I understand you people are using 1 anyway. So they actually do that. I'm confused now.

In any case, IMO non of that changes what my code achieves here.

**Comment by Havner** [comment]
> > The drawback here is that when people start playing games, they need to learn how to disable Desktop mode... Which I really don't like. 🙁
> 
> From what I understand you earlier people are using 1 anyway. So they actually do that. I'm confused now.

Anyway, both approaches have drawbacks (either you have to disable/enable the Desktop mode or create a profile per game). Not sure this can be solved in any way. What I am trying to do here is to make sure that both those solutions can work well and let people choose which one they want. I wouldn't want to force any settings on people that can hinder one or another.

**Comment by Valkirie** [comment]
I'm fine with that pull request, as is. I'm just going to implement a few pre-pinned hotkeys (including Desktop layout) and a physical toggle on main controller page to make sure people understand when the option is turned on.

**Comment by CasperH2O** [comment]
> Enable desktop mode on application start (OPTION): [yes|no|restore previous state]

I find it odd to make a setting for having it enabled on boot yes or no. Instead I propose we make the Desktop layout being on or off a setting and have it on by default.

**Comment by Havner** [comment]
> I find it odd to make a setting for having it enabled on boot yes or no. Instead I propose we make the Desktop layout being on or off a setting and have it on by default.

Please elaborate, I don't understand what you mean here.

**Pull request merged**
