### PR TITLE
DesktopProfileOnStart Default False

### PR DESCRIPTION
**Pull request by CasperH2O**

### CODE REVIEW

**Comment by Havner** [comment]
Have you tested it? Have you changed it through the settings window in VS?

Look at those files:
https://github.com/Valkirie/HandheldCompanion/blob/main/HandheldCompanion/Properties/Settings.settings
https://github.com/Valkirie/HandheldCompanion/blob/main/HandheldCompanion/Properties/Settings.Designer.cs

**Comment by CasperH2O** [comment]
I adjusted it through here, compiled and booted, on a fresh run it starts off.

image

**Comment by CasperH2O** [comment]
I'll double check.

**Comment by Valkirie** [comment]
Indeed you were missing two other files modification. Strange.

**Pull request closed without merging**
