### PR TITLE
Localization Update

### PR DESCRIPTION
**Pull request by twjmy**

### CODE REVIEW

**Comment by Valkirie** [comment]
Thank you very much. I've been adding a lot of hardcoded texts lately. Do you want me to merge as is, or will you be going through the whole software?

**Comment by twjmy** [comment]
> Thank you very much. I've been adding a lot of hardcoded texts lately. Do you want me to merge as is, or will you be going through the whole software?
> _Originally posted by @Valkirie in https://github.com/Valkirie/HandheldCompanion/issues/593#issuecomment-1565936951_

Well, you can merge it first. I may try going through the whole lately.
btw, where's those part gone?
image
I cannot find them below here https://github.com/Valkirie/HandheldCompanion/blob/f7f74d82dd9675c74a55162c647b3c511a14bf90/HandheldCompanion/Views/Pages/SettingsPage.xaml#L1116

**Comment by Valkirie** [comment]
> > Thank you very much. I've been adding a lot of hardcoded texts lately. Do you want me to merge as is, or will you be going through the whole software?
> > _Originally posted by @Valkirie in https://github.com/Valkirie/HandheldCompanion/issues/593#issuecomment-1565936951_
> 
> Well, you can merge it first. I may try going through the whole lately.
> btw, where's those part gone?
> image
> I cannot find them below here https://github.com/Valkirie/HandheldCompanion/blob/f7f74d82dd9675c74a55162c647b3c511a14bf90/HandheldCompanion/Views/Pages/SettingsPage.xaml#L1116

They were removed. Now there is only the Quiet mode within quick tools. On first activation, it'll ask for consent and then be enabled.

**Comment by twjmy** [comment]
> > ...
> 
> They were removed. Now there is only the Quiet mode within quick tools. On first activation, it'll ask for consent and then be enabled.
> _Originally posted by @Valkirie in https://github.com/Valkirie/HandheldCompanion/issues/593#issuecomment-1565947323_

ok then. maybe my version isn't latest or something goes wrong.

**Pull request merged**
