### PR TITLE
Update Build & Release Pipeline

### PR DESCRIPTION
**Pull request by CoryManson**
Adds Build & Release actions to workflow.

- Executes on Pull Request when target branch is main:
   - Does not create a release, only used for build validations
   - Uses existing tag version for installer
- When executed manually, has options to create release:
    - Generates changelog between previous tag & HEAD
    - Builds normal installer & offline installer
    - Token replace in .iss files to inject new version into the installer (no need to manually update the version in ControllerService.iss)

Pipeline does not upload any build artifacts to ensure no installer gets out into the wild unintentionally. 

image

Example Release: https://github.com/CoryManson/HandheldCompanion/actions/runs/5483795225
Example Pull Request Validation Run: https://github.com/CoryManson/HandheldCompanion/actions/runs/5483784484

### CODE REVIEW

**Comment by CasperH2O** [comment]
@CoryManson I went over it. First off, thank you very much!

1. I don't see the number update for the ControllerService/AssemblyInfo1.cs and HandheldCompanion/HandheldCompanion.csproj files. Am I missing something? See this example: https://github.com/Valkirie/HandheldCompanion/commit/fbfa2340e29ddeb08832132d58802f7fdc621e41
2. Can you leave out the changelog/commit list? We write these by hand as non technical users have no clue how to read them.
3. I like the idea that it builds on creating a pull request, how and where do we then check that it succeeded or it's result?

**Comment by CoryManson** [comment]
> @CoryManson I went over it. First off, thank you very much!
> 
> 1. I don't see the number update for the ControllerService/AssemblyInfo1.cs and HandheldCompanion/HandheldCompanion.csproj files. Am I missing something? See this example: [fbfa234](https://github.com/Valkirie/HandheldCompanion/commit/fbfa2340e29ddeb08832132d58802f7fdc621e41)
> 2. Can you leave out the changelog/commit list? We write these by hand as non technical users have no clue how to read them. Is it possible to place a format  template there like we have here: https://github.com/Valkirie/HandheldCompanion/wiki/Release
> 3. I like the idea that it builds on creating a pull request, how and where do we then check that it succeeded or it's result?

Thanks for the feedback.

1. I wonder if it may be best for you to keep version bumping in source control. It is possible to have the workflow do it for you but I'm not sure what best practice should be (https://edi.wang/post/2019/3/1/incremental-build-number-for-net-core-via-azure-devops). The workflow can either:
    1. Modify the files and release, discarding the changes after the workflow has run
    2. Modify the files, push the changes straight to main (not ideal) and release
    3. Not modify anything and just build what's in source (this may be the simplest and easiest)
2. Yep, will update to include the demo text. Let's have the workflow create the release in draft mode first so then you can update the text before the release becomes public.
3. The build shows up on your PR:
image

**Comment by CoryManson** [comment]
Screenshot of a release created by workflow in draft mode. From here you would edit, add your notes then publish.

image

**Comment by CoryManson** [comment]
Have updated workflow to modify files and commit as requested. 

The workflow will now open a pull request with new version.

Notably, I've hardcoded the version on the .iss files to 0.0.0.0, the workflow now sets the version on the command line as there's no need to change that version in source control.

Actions will need to have permission to open a PR:

image

Actions will also need to be enabled. To keep a list of approved actions, the following should work:

image

**Pull request merged**
