### PR TITLE
Add Ayaneo 2 device.

### PR DESCRIPTION
**Pull request by CasperH2O**

### CODE REVIEW

**Comment by chris-calo** [comment]
@CasperH2O probably worth adding `Ayaneo 2` support to the `README.md` file, as well

**Comment by CasperH2O** [comment]
> @CasperH2O probably worth adding `Ayaneo 2` support to the `README.md` file, as well

Yes, as soon as the pull request is merged. :-)

**Comment by Valkirie** [comment]
> > @CasperH2O probably worth adding `Ayaneo 2` support to the `README.md` file, as well
> 
> Yes, as soon as the pull request is merged. :-)

Is this confirmed working ?

**Comment by CasperH2O** [comment]
I made this based on information provided by Frank who was able to test Motion Assistant with a device.

Can't hurt either way, I expect the Geek device to be similar but with a different product name.

**Comment by CasperH2O** [comment]
> @CasperH2O probably worth adding `Ayaneo 2` support to the `README.md` file, as well

@chris-calo I may not have expressed myself correctly, I prefer to edit the readme file on GitHub directly as it allows for previewing the format.

You make a valid point though, could have done it together with the other things in the PR.

**Pull request merged**
