### PR TITLE
Add ApplicationFrameHost.exe to ProcessManager ignore list.

### PR DESCRIPTION
**Pull request by CasperH2O**
Oops, forgot to branch. Tested locally on a few games, seemed OK.

### CODE REVIEW

**Comment by Valkirie** [comment]
Did you check with an actual UWP game ?

**Comment by CasperH2O** [comment]
No. Do you know of any?

**Comment by Valkirie** [comment]
Minecraft, Sea of Thieves

**Comment by CasperH2O** [comment]
Code was applied and tested in other branch.

**Pull request closed without merging**
