### PR TITLE
Implement brightness and volume hotkeys

### PR DESCRIPTION
**Pull request by Havner**

### CODE REVIEW

**Comment by Havner** [comment]
Few remarks here:
1. The seemingly strange volume calculation is to make it snap to %5==0 values, even taking into consideration float rounding errors. Values like 30.00001 and 29.9999 will be treated like 30 and will got to 25/35 on decrease/increase respectively. But values likes ~31 will go to 30 on decrease. Just like values like ~34 will go to 35 on increase.
2. I had to move HasBrightnessSupport initialization to the constructor. Either that or the IsEnabled on hotkeys needs to be moved to some SystemManager_Initialized() callback (that would need to be created in HotkeyManager). Either is fine with me. This was less code and HasVolumeSupport is already initialized in the ctor.
3. The hotkeys themselves are kinda poor in terms of usability. This is outside of the scope of this PR, but I feel this is something that needs addressing at some point. Basically when you map e.g. OEM1+Up for IncVol and OEM1+Down for DecVol you expect to be able to hold OEM1 and press Up/Down to change the value. Right now you have to press OEM1, press Up, release Up, release OEM1 and just then the hotkey is triggered. Which means you need to constantly press and release OEM1 to increase few times in a row.
4. I've tried to switch the hotkeys from OnKeyUp to OnKeyDown (InputsHotkey ctor) but that was bugged as hell or I don't understand how it's supposed to work. With hotkey set like this every time you bind it you get "Long" binding, even though you press it very shortly. And then when you use it each hotkey gets triggered few times on one regular OEM1+Up press.

**Comment by Valkirie** [comment]
I guess we need to work this function and this check : https://github.com/Valkirie/HandheldCompanion/blob/5d9e229ff7c11e13ba77042ccb03bd8e7eb99599/HandheldCompanion/Managers/InputsManager.cs#L547

**Comment by Havner** [comment]
I still have few gripes with how hot keys chords work. Me wanting to add the mute keys is just one of the things that isn't working as I think it should.

What you say here is right but I don't think this belongs to this pull request. This just adds new hotkeys that work. 

The rework/improvement of handling hotkeys is a bigger topic than this PR.

**Comment by Havner** [comment]
Switched the new hotkeys to keyDown mode. Requires #512 to work well.

**Pull request merged**
