### PR TITLE
Added Custom overlay mode

### PR DESCRIPTION
**Pull request by micdah**
## In short

Keeps RTSS and HWINFO running, but without injecting / refreshing own OSD UI into it, relying on the user to configure their own overlay in RTSS

## Motivation for addition

I'm a newcomer to Handheld Companion, and the only thing keeping me from using it as an Armory Crate replacement, is that the newest version with OSD support interferes with my RTSS setup, where I have a more detailed overlay configured, also using HWinfo.

This PR adds a separate `Custom` mode, which acts as if needs `OnScreenDisplay` and `OnScreenDisplayComplex` (_to also get HWinfo_) are requested, but without `OSDManager.RefreshTimer` running (_no need to keep sending an empty string to RTSS every second in the background_).

I have added `EnableOSD` toggling also, which is toggled on settings changes, so that when overlay is enabled (any mode) RTSS is asked to enable OSD, otherwise it's asked to disable OSD.

That way, when using `Custom` and toggling to `Disabled`, the user configured overlay is hidden - whereas if we don't toggle `EnableOSD` in RTSS, the user configured overlay will remain - as we are not injecting it through `OSD.Update`.

I think this might also address issues such as this: https://github.com/Valkirie/HandheldCompanion/issues/703

## Thoughts for improvements

I'm not a big fan of using the index of the profile in `OverlayLevel`, I can already see a clash between this PR and this other one https://github.com/Valkirie/HandheldCompanion/pull/648 in which we are both using index `4` for different things.

That said, changing the type of an existing setting is probably more effort that it's worth just figuring out the merge conflicts 😄

### CODE REVIEW

**Comment by CasperH2O** [comment]
Hey Michael! Very nice PR. Some thoughts from my end:
- Nice clean code, commenting and even localization. 😄 
- Instead of adding a custom level, why not add a setting to just not close HWInfo/RTSS if it's not used by HC? Wouldn't that accomplish the same effect?
- It's usually best to first discuss if you want to contribute something to HC up front so we can talk about the approach and or what we already have in the pipeline in terms of development.
- I feel the option "Custom" implies the user can configure something within HC what they want to show, which is what @Valkirie had in mind for a future update.

**Comment by micdah** [comment]
> Hey Michael! Very nice PR. Some thoughts from my end:
> 
> * Nice clean code, commenting and even localization. 😄

I tried to keep to existing code conventions, but felt adding some comments wouldn't hurt - as much to help myself understand the code 🙈 

> * Instead of adding a custom level, why not add a setting to just not close HWInfo/RTSS if it's not used by HC? Wouldn't that accomplish the same effect?

Very true, I just couldn't figure out the cleanest approach to be honest - there are also these "keep X open after HC closes" settings (_which may need some work perhaps, as they seem to only be evaluated on shutdown on the app, but not when needs change in the platform manager, i.e. if I disable overlay then HWINFO can be killed even when "keep open" is enabled in settings, but for RTSS it's never killed this way - so some perhaps odd behaviour there_).

A benefit of "Custom" level to me, was also that by disabling I could get HC to terminate RTSS/HWINFO, when I don't need the overlay, sparing the ressources to run those, as opposed to having separate keyboard shortcut outside of HC to toggle overlay in RTSS. Having it as a separate level, made it feel more integrated.

If HC could trigger the overlay editor plugin directly, we might even be able to have an "Edit" button which opens the RTSS Overlay Editor plugin, thus enabling the user to more easily setup the overlay they want entirely within RTSS - but without knowing how to navigate there 🤔 

It's kind of a hack, to be sure.

As RTSS has HWINFO integration, I also prefer having RTSS poll HWINFO for sensor data and include it in the overlay as `%CPU Package Power%` e.g., rather than having HC polling HWINFO and then having to send new overlay hypertext on each update (_I don't know the cost of parsing the hypertext in RTSS, but I would guess it's less having RTSS parse the hypertext once and then self updating placeholders for sensor data directly_).

> * It's usually best to first discuss if you want to contribute something to HC up front so we can talk about the approach and or what we already have in the pipeline in terms of development.

I know 🙈  I kind of jumped the gun on it, you know how it is, I had some free time and was tinkering with my ROG Ally, wanting to get away from Armory Crate and find something else - and felt HC was interesting, but was just furiated by it's interference with my RTSS setup.

> * I feel the option "Custom" implies the user can configure something within HC what they want to show, which is what @Valkirie had in mind for a future update. Perhaps rename it to "External"?

Great idea for naming, agree on `External` being a better name - would also be interesting to discover whether it's possible to open the overlay editor directly in RTSS from HC.


## Off topic

I think there is some issues with `ReadTDP` on devices where HC falls back to calculating actual limits off of % limit data from HWINFO. On my ROG Ally I can see in the debugger that the cpu watchdog is trying to update the TDP on each update, i.e. each second, because on each read it's always off as the conversion of "cpu power in watts / percent from limit * 100" seemingly has too much inaccuracy, perhaps on this particular device.

It's likely that under high load, when the CPU is at or near the limit, this calculation is more precise, but under low usage (< 50%) it seems to be too inaccurate.

Also it seems HC favors the percent calculation over PL1/PL2 data from HWINFO, if they are available. 🤔 

Also I was curious as to why HC wasn't using the `Processor` manager, to check if the underlying platform can provide the TDP limit values for stamp/slow/fast, as far as I can tell both the Intel and AMD providers should in most cases be able to provide those values.
On the ROG Ally it seems they are still missing as RyzenAdj doesn't have the correct tables yet, so we just get `NaN` (_had to try it out now that I had development environment setup on the device_).


## Next steps

I'm totally down for doing iterations on the PR, I guess these are the outstanding issues

- Should I rename it to `External` to better signal intent
- Should it instead be separate settings rather than a overlay level
  - What should the setting(s) be, and how ought they to work, in particular how should "platform needs" be determined
  - Could settings also handle the use-case of disabling OSD via HC even when using your own custom overlay, so as the user could use HC to toggle OSD rather than having to manually setup RTSS toggle hotkey outside of HC
  - I guess there could be a quick tools shortcut that could be added, which invokes the `EnableOSD(true | false)` as I do now

My personal preference would be for having it as a separate overlay level with appropriate name, where `EnableOSD(...)` is invoked appropriately as well so both are handled by a single setting 😄

**Comment by CasperH2O** [comment]
> A benefit of "Custom" level to me, was also that by disabling I could get HC to terminate RTSS/HWINFO, when I don't need the overlay, sparing the ressources to run those, as opposed to having separate keyboard shortcut outside of HC to toggle overlay in RTSS. Having it as a separate level, made it feel more integrated.

Yes, I realized this extra benifit later also, combined wit renaming it "External" this would actually be quite nice as opposed to just having that setting.

> If HC could trigger the overlay editor plugin directly, we might even be able to have an "Edit" button which opens the RTSS Overlay Editor plugin, thus enabling the user to more easily setup the overlay they want entirely within RTSS - but without knowing how to navigate there 🤔

I'm not at all familiar with RTSS overlays through it's own editor, but it doesn't feel ideal or something we would want.

> As RTSS has HWINFO integration, I also prefer having RTSS poll HWINFO for sensor data and include it in the overlay as `%CPU Package Power%` e.g., rather than having HC polling HWINFO and then having to send new overlay hypertext on each update (_I don't know the cost of parsing the hypertext in RTSS, but I would guess it's less having RTSS parse the hypertext once and then self updating placeholders for sensor data directly_).

This would be nice for sure, and probably more efficient. Perhaps not for this PR but something the could be investigated/prototyped seperate.

> I know 🙈 I kind of jumped the gun on it, you know how it is, I had some free time and was tinkering with my ROG Ally, wanting to get away from Armory Crate and find something else - and felt HC was interesting, but was just furiated by it's interference with my RTSS setup.

Your enthusiasm is very welcome here. 😁 

> I think there is some issues with `ReadTDP` on devices where HC falls back to calculating actual limits off of % limit data from HWINFO. On my ROG Ally I can see in the debugger that the cpu watchdog is trying to update the TDP on each update, i.e. each second, because on each read it's always off as the conversion of "cpu power in watts / percent from limit * 100" seemingly has too much inaccuracy, perhaps on this particular device.
> 
> It's likely that under high load, when the CPU is at or near the limit, this calculation is more precise, but under low usage (< 50%) it seems to be too inaccurate.
> 
> Also it seems HC favors the percent calculation over PL1/PL2 data from HWINFO, if they are available. 🤔

I've been trying to convince @Valkirie for months now to remove this code, but haven't had much luck. 😛 Using HWInfo for this when available is not ideal. I think we did check Processor manager, but don't recall why it isn't used. Perhaps it's nor reliable enough for supporting all handhelds.

> I'm totally down for doing iterations on the PR, I guess these are the outstanding issues
> 
>     * Should I rename it to `External` to better signal intent
> 
>     * Should it instead be separate settings rather than a overlay level
>       
>       * What should the setting(s) be, and how ought they to work, in particular how should "platform needs" be determined
>       * Could settings also handle the use-case of disabling OSD via HC even when using your own custom overlay, so as the user could use HC to toggle OSD rather than having to manually setup RTSS toggle hotkey outside of HC
>       * I guess there could be a quick tools shortcut that could be added, which invokes the `EnableOSD(true | false)` as I do now
> 
> 
> My personal preference would be for having it as a separate overlay level with appropriate name, where `EnableOSD(...)` is invoked appropriately as well so both are handled by a single setting 😄

I'm ok with it now just being an option in the drop down. Alternatively it could be a toggle beneath the drop down that states something like "Using an external RTSS OSD Configuration". That way you could perhaps even combine them.

I prefer to have it be part of the dropdown for now though, it's very clear. 

Lets wait and see what @Valkirie thinks.

**Comment by micdah** [comment]
>> As RTSS has HWINFO integration, I also prefer having RTSS poll HWINFO for sensor data and include it in the overlay as %CPU Package Power% e.g., rather than having HC polling HWINFO and then having to send new overlay hypertext on each update (I don't know the cost of parsing the hypertext in RTSS, but I would guess it's less having RTSS parse the hypertext once and then self updating placeholders for sensor data directly).

> This would be nice for sure, and probably more efficient. Perhaps not for this PR but something the could be investigated/prototyped seperate.

Within RTSS when you configure an overlay, you have the option to setup "Data Sources" which can be provided either by RTSS (_such as framerate_), but it also have native integration with HWINFO, so it can pull all HWINFO sensors also.

To use it in the RTSS hypertext, it first needs to be added as a data source - but I don't think this can be done via the hypertext alone, perhaps it can be done via the RTSS API, but I'm guessing.


> I've been trying to convince @Valkirie for months now to remove this code, but haven't had much luck. 😛 Using HWInfo for this when available is not ideal. I think we did check Processor manager, but don't recall why it isn't used. Perhaps it's nor reliable enough for supporting all handhelds.

My suggestion / approach might perhaps be some sort of prioritized list of strategies, whereby HC goes with the highest priority one available. E.g.

- Processor manager
- HWINFO PL1/PL2 etc.
- HWINFO % Fast/Slow Limit

So for example from `RyzenAdj` we either get `-1` if the API is unavailable I believe, or we get `NaN` if it doesn't have tables for it etc., so we should be able to figure out whether the returned data is reliable - and if it is, could perhaps be used.

Likewise, if HWINFO doesn't give us PL1/PL2, then we know we need to fallback to the perhaps inaccurate approach.

Perhaps for the inaccurate strategy there ought also be either a backoff strategy (_because we know the inaccuracies might lead HC to adjust TDP constantly because it incorrectly thinks the limit it not set correct_), where after X attempts if stops trying again, until the desired TDP is changed in HC. Or maybe the comparison should be done with a `delta` so that `ReadTDP` just needs to be "near" desired TDP.

Could even be based on "limit %", i.e. say we read "90% Fast Limit", then we can reasonably assume the CPU Package Power ought to be fairly close to actual Fast limit, so we would like read TDP to be very close to desired in this case. Whereas if we read say "25 % Fast Limit", we know the read package power might be very far off, and our conversion thus have a higher inaccuracy and we should compare using a larger `delta`.

I'm not even sure why the watchdog is even there - if we invoke TDP change, and it's not set correctly - couldn't that only be becuase some other program is interfering? Ought the user then not instead have a warning that some ofter software is tinkering with TDP also, and the user should stop / uninstall said software / driver.

Ideally TDP should be set, and we ought not to check it again? Or is it just the case that many devices have vendor software that can't help itself tinkering with the TDP also, so we need to re-set it constantly?

**Comment by micdah** [comment]
@CasperH2O oh, something else I "discovered" (_becuase i already had HWINFO installed and configured_), HC relies on various sensor readings, but in HWINFO you can delete or disable sensors, so if a user already has HWINFO installed or later decides to tinker around, they might end up disabling or removing a sensor in HWINFO which HC relies on.

It makes sense to disable unused sensors in HWINFO, as some take up some time and ressources to read out, especially stuff like SMART info for drives or some battery statistics. That's why I had most stuff disabled, including stuff HC actually wanted 🙈

**Pull request merged**
